### PR TITLE
Initialize rabbits as down

### PR DESCRIPTION
**Pull request by jameshcorbett**
WIP until Fluxion is updated to support a `status` parameter to the `FluxionResourcePoolV1 class. 

Edit: done.

### CODE REVIEW

**Comment by jameshcorbett** [comment]
Depends on https://github.com/flux-framework/flux-sched/pull/1125 and https://github.com/flux-framework/flux-sched/pull/1123

**Review by grondo — APPROVED** [review]
FWIW, LGTM!

**Comment by vsoch** [comment]
The wabbits are down, you say? Did you try giving them carrwots? :carrot: :carrot:

**Comment by jameshcorbett** [comment]
It's worth everything @grondo ! Setting MWP.

**Pull request merged**
