### PR TITLE
Rabbit env vars

### PR DESCRIPTION
**Pull request by jameshcorbett**
As discussed in #104, export the hostname of the rabbit local to each compute node as the FLUX_LOCAL_RABBIT environment variable.

### CODE REVIEW

**Review by grondo — APPROVED** [review]
This looks good to me!

My only suggestion would be to add a test with multiple rabbits with multiple nodes to further exercise selection of the correct rabbit hostname in the shell plugin. I'd call that optional though and leave it to you whether to implement the extra testing.

**Comment by grondo** [comment]
One other worry could be the size of the eventlog entry when there are many rabbits and many nodes. I don't think there will be a problem there, but we might want to test the largest entry we expect to see just in case.

**Comment by jameshcorbett** [comment]
> This looks good to me!
> 
> My only suggestion would be to add a test with multiple rabbits with multiple nodes to further exercise selection of the correct rabbit hostname in the shell plugin. I'd call that optional though and leave it to you whether to implement the extra testing.

Force-pushed to add another test. I'll set MWP.

**Comment by jameshcorbett** [comment]
> One other worry could be the size of the eventlog entry when there are many rabbits and many nodes. I don't think there will be a problem there, but we might want to test the largest entry we expect to see just in case.

I think all the rabbits will be attached to nodes with contiguous IDs, so the hostlists should be relatively compact, along the lines of `elcapitan[0-18]` rather than `elcapitan[201,302,305,307,...]`. But yeah maybe a test with a thousand rabbits or something in that ballpark would be good.

**Pull request merged**
